### ISSUE TITLE
Many branches, one cs: url

### ISSUE THREAD

**Issue by stub42** [canonical/jujucharms.com#102]
I have many PostgreSQL branches. I appear to have a single cs:trusty/postgresql charm. I have no idea which branch this corresponds to.

Not that it matters, as it is most probably the _wrong_ one. As 'juju deploy' only accepts cs: and local: URLs, the first step of my demo is 'how to create a local repository' followed by 'how to install bzr' followed by 'how to branch this lp: url into your repository'.

I need cs: URLs for all my charm branches on Launchpad. I need to be able to discover them using the charm store. This will bridge the gap between developers, who work with branches, and the charm store.

The work around is to use juju-deployer which understands branches, and avoid the charm store and bundles.

**Comment by mitechie** [comment]
Currently we only pull in trunk. It's what juju has been loading for the
deploy command since the beginning and we have concerns with deduplication
and making sure users get the "best charm". Changing this pattern is meant
for a new feature called channels slowing for specified alpha, beta,
nightly, and stable builds. That feature is still a ways out but scheduled
for this cycle.

**Comment by frankban** [comment]
This is attenuated by the new charms/bundles publishing model.
I am closing this bug as out of scope for jujucharms.com.
