### ISSUE TITLE
Cache html pages

### ISSUE THREAD

**Issue by kapilt** [canonical/jujucharms.com#12]
Currently none of the html pages is cached. This includes both static pages and those with query strings. Most of the site latency can be attributed to this being missing.

**Comment by fabricematrat** [comment]
@kapilt Fix delivered on jujucharms.com

**Comment by kapilt** [comment]
i see no evidence of caching by squid on any of the html pages.

```
kapil@realms-slice:$ curl -o render.html -i https://jujucharms.com                                                                                                                                                                                          
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14049  100 14049    0     0  22776      0 --:--:-- --:--:-- --:--:-- 22806
kapil@realms-slice:$ head render.html 
HTTP/1.1 200 OK
Date: Fri, 19 Dec 2014 10:43:02 GMT
Server: Apache/2.4.7 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Content-Length: 14049
Expires: Fri, 19 Dec 2014 11:43:02 GMT
Cache-Control: max-age=3600, public
X-Cache: MISS from localhost
X-Cache-Lookup: MISS from localhost:3128
Via: 1.1 localhost (squid/3.3.8)
```

what was done seems to be effective for browser instruction, but squid is still misconfigured.

Effectively this means its only useful to repeat visitors to a page for a few hrs, not to new users.

**Comment by mitechie** [comment]
We're still working through the squid side. We added proper headers to the pages now in this release which you noticed by browsers caching now. However, the pages don't end in an extension like .html in order to direct squid to cache those. We need to find another path to that. We've added squid cache directives for most static urls ending in contentions like png/jpg however I want to make sure we avoid situations where we're maintaining a list in squid of urls we think should be treated as static.

Leaving this open with the task to investigate if there's a way to direct squid via headers or something other than the url itself, however this is a low priority bug with respect to the other things we have targeted for the next release and so we'll make this more of a slack task to improve from here.

**Comment by kapilt** [comment]
having squid respect cache headers regardless of file extension would be a
better choice.

**Comment by kadams54** [comment]
Setting up client-side caching on all HTML (e.g., Cache-Control headers) causes more problems that it solves. I think we're better off with profiling to identify performance bottlenecks and optimizing things on the backend first. Due to clients (particularly Safari) aggressively caching and not displaying the correct content when users login/logout, we've set `Cache-Control: no-cache` for all HTML for the time being.
