### ISSUE TITLE
Cache JavaScript and remove where unused

### ISSUE THREAD

**Issue by kapilt** [canonical/jujucharms.com#13]
The javascript resources aren't being cached by the site. We're loading about 85k of javascript in two requests every page. Afaics we're not actually using javascript anywhere. We should disable and minimize our usage of js redundant resources till their actually needed.

**Comment by fabricematrat** [comment]
@kapilt Fix delivered on jujucharms.com

**Comment by kapilt** [comment]
as per my response in #12 adding a header doesn't fix this issue. Squid still isn't caching, and the home page still loads 100k of js to do a user login link and twitter feed?

**Comment by mitechie** [comment]
The JS feeds 
- the twitter feed
- the latest blog content
- provides some UX on the search box to pretty up the urls to proper clean search urls
- User login/drop down menu work.
- Cookie ack handling

From cache the page load in chrome dev tools show 140k total.

The one thing that we meant to fix, but failed to get correct, is that the JS isn't cached in squid because it's not like other static assets ending in .js. We updated squid in this release to catch .png,.jpg,.css,.js etc. However the combo urls don't match this so we need to make another patch to those squid caches. 

Leaving this bug open in order to correct this. The other thing I want to look at is we're still making 3 JS requests when I think we should be able to combine that down to one.

**Comment by frankban** [comment]
This seems to be fixed now.
