### ISSUE TITLE
Search results not showing latest charms

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#130]
Latest version of hacluster charm is -20 as shown by:

```
⟫ curl -s https://api.jujucharms.com/v4/trusty/hacluster/meta/any | jq .Id
"cs:trusty/hacluster-20"
```

But when I search for it at https://jujucharms.com/q/hacluster the [link for Trusty](https://jujucharms.com/hacluster/trusty/15) points to -15

**Comment by mitechie** [comment]
The search results are returning more than one result for some reason:

https://api.jujucharms.com/v4/search?text=hacluster

@urosj and @rogpeppe any ideas why this one appears twice for the base entity?

**Comment by urosj** [comment]
Hi, @sparkiegeek 

Rev 15 was owned by charmers [1], while new one is owned by openstack-charmers [2](and correct me if this is wrong). So it looks like there's a bug in charmstore that does not delete an old entry in some cases when change of ownership happens in promulgated charms. 

We'll take a look, thanks.

[1] https://api.jujucharms.com/charmstore/v4/trusty/hacluster-15/meta/extra-info/bzr-owner
[2] https://api.jujucharms.com/charmstore/v4/trusty/hacluster-20/meta/extra-info/bzr-owner

**Comment by urosj** [comment]
@sparkiegeek duplications fixed.

https://api.jujucharms.com/v4/search?text=hacluster

However, looking at https://jujucharms.com/q/hacluster it seems there is a UI bug, because we list all the community recommended charms that implement hacluster interface before actually showing hacluster as result. And it is the wrong version, it should be revision 20. 

API search returns HAcluster in results.

https://api.jujucharms.com/v4/search?text=hacluster&include=charm-metadata&include=bundle-metadata&include=extra-info/bzr-owner&include=extra-info/commercial&include=bundle-unit-count&include=stats&limit=400&autocomplete=1&owner=&sort=-downloads,owner

@mitechie, @kadams54: Leaving the issue open so that SF guys look a it. Currently a non-promulgated version is shown and is thus really ranking really low.

**Comment by urosj** [comment]
Correcting. It looks like caching was in play. So results are ok now. Closing the bug.

**Comment by urosj** [comment]
After several reloads, the proper revision is not shown in the results anymore.
