### ISSUE TITLE
Add new contributor to community page

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#132]
Please replace Cory Johns with Chris Donati, and change the heading to "PaaS Solutions"

Description: Chris Donati has been working on improving the AppScale platform, which lets you deploy your Google App Engine application on any cloud, public or private. He lives in Santa Barbara, California, where he's been trying to get better at the game of Go.

Here's the charm: https://jujucharms.com/appscale/precise/1

![unnamed](https://cloud.githubusercontent.com/assets/1264109/9115375/c2b0b442-3c2c-11e5-816d-c2d9a160a919.jpg)

**Comment by Lucapaulina** [comment]
After conversations in Seattle design needs to revamp the contributor section so that it is clear where to contribute and to show the appscale charm.

@castrojo Do we want to push contribution on this? Can you take a look at https://jujucharms.com/community and tell @elvirafigueras and me what is changes are needed?

**Comment by castrojo** [comment]
This one is done, we can close this, @Lucapaulina I'll open a new bug for the revamp Antonio wanted.
