### ISSUE TITLE
G+ sharing of charms should include the charm icon 

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#14]
There's also a difference when you copy and paste the link into a G+ post and when you click the Google share link in the footer on the page. 

From @castrojo original report:

I wanted to share a charm I found on jujucharms.com but when I click G+ it just gives me a blank setting. We should feature the charm partner by leveraging microdata: https://developers.google.com/+/web/snippet/

The charm icon + description should be enough. This will also seed search engines with the charm's metadata, which is probably a good thing. See also: http://schema.org/

**Comment by kadams54** [comment]
I've verified the microdata is already in place. It also passes Google's verification tool, but the icon doesn't display there either. I suspect the icon problem is that the image is SVG, rather than PNG, GIF, or JPEG. I'm not sure why the name and description aren't being used; I'm going to play around with other approaches (OpenGraph, meta tags in the head) to see if any of those are more successful.

For what it's worth: I've dealt with microformats in a similar situation. We had a terrible time getting Google to pick up on the additional rich data. We ended up paying an SEO consultant to work through his contacts within Google to get the additional info showing up. Furthermore, in the end, we never did get the icons to display. That was in search results, not G+ sharing, but I'm still leery.

**Comment by mitechie** [comment]
That's wrap up and land what we can on this. We can revisit it in the next
cycle of work after the release gearing towards the idea of proxying the
icons through the application. It's starting to be a case of biting off
more than we want to chew before the release.

**Comment by kadams54** [comment]
Agreed. We talked about it in channel and decided to land work that would add OpenGraph markup to expand the number of social/search crawlers that can grok the site. A second card was setup to address the SVG icons separately.

**Comment by kadams54** [comment]
Quality SVG converters seem to be in short supply. I tried two different wrappers around Cairo - CairoSVG and svg2png - and one produced a blank image while the other generated a botched version of the icon. I tried a javascript version of svg2png that wrapped around PhantomJS and that also made a blank image. If we can find a way to make PNGs from SVGs, then this won't be that hard to solve.

**Comment by 0atman** [comment]
FWIW, we use imagemagick for the web team's new assets server for image manipulation and conversion?

**Comment by mitechie** [comment]
We've landed some improvements but need to get the svgs to pngs for this to really work properly.

**Comment by mitechie** [comment]
Targeting to the next release. The feature scope required here grew and we're working on it for the next release.

**Comment by mitechie** [comment]
Didn't make 0.1.9 going out now but some of the deps did. It should make the next release.
