### ISSUE TITLE
Sign In Gives Server Error

### ISSUE THREAD

**Issue by Koxzi95** [canonical/jujucharms.com#140]
Trying to sign in from any page gives me a server error and 'Sorry for the inconvenience, please pop back soon.' message. 

I believe it's during/after the OpenID process.

**Comment by tcfunk** [comment]
+1

**Comment by mitechie** [comment]
Do you all have LP user accounts? There's a known issue atm where if you have an SSO account, but not an LP account that the login fails as an LP account is expected. 

We're working on a solution to this but it'll be a more long term endeavor.

if you do have an LP account can you share the LP username so that we can investigate?

Thanks and sorry for the trouble.

**Comment by mitechie** [comment]
I'm so sorry, LP == Launchpad.net account. It adds onto your Ubuntu SSO  
account. I forget not everyone east/sleeps/breaths our shortcuts.                                                                                                                                                                                                                          

We use the nickname field that a Launchpad account adds to a user's SSO  
information. We're working with those two teams to figure out a better  
solution to this. Your user url in jujucharms.com is:

```
jujucharms.com/u/$launchpad-nickname  
```

Can you create a launchpad account and verify that corrects things for you?  
I'm definitely going to keep the bug open as we work on this with the SSO  
and Launchpad teams to make this not a requirement, however I think it'll  
unstick you while we work on that.

**Comment by tcfunk** [comment]
That worked for me, thank you!

**Comment by Koxzi95** [comment]
@mitechie That also worked for me as well.
