### ISSUE TITLE
Shortcut to CLI snippet cut off

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#142]
See picture, this seems to be a recent regression:

![selection_014](https://cloud.githubusercontent.com/assets/1264109/9443602/f1146f28-4a4f-11e5-83c8-c4f7611f9508.png)

**Comment by castrojo** [comment]
When I click on the actual text it fixes the command snippet, and when you click off of it again it cuts off, seems like it right justifies instead of left justifies.

**Comment by mitechie** [comment]
This is intentional.. Since the 'juju deploy' part is copied on everything and not helpful in telling what's going on, clicking in and copying the copy button both add the 'juju deploy' text for you. 

The idea is the textbox shows you the charm ID used to deploy, but you only get the full command when interacting. Otherwise the text is cut off on the end when there are usernames and long charm names and the important information we'd rather keep.
