### ISSUE TITLE
Search results return pages that 404

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#153]
To replicate, do a search for docker, then click on "block storage broker":
https://jujucharms.com/q/docker

URL it's trying to get to is: https://jujucharms.com/block-storage-broker/trusty/1

**Comment by urosj** [comment]
Thanks for pointing this out, @castrojo 

There is no trusty block-storage-broker charm, only precise, but store front assumes that there is one.

**Comment by mitechie** [comment]
Yes the search results have collapsed and shows both versions. Maybe this is related to the sorting bug as well if there's a bug in the series collapsing code. 

Actually maybe it's because there's both:

Id: "cs:precise/block-storage-broker-8"
and 
Id: "cs:~charmers/trusty/block-storage-broker-1"

both will be 'owned' by ~charmers and so it's collapsing. however, both are not promulgated (thus there is not trusty block-storage-broker. Should that trusty version be promulgated? Is this a thing eco can fix or is that charm not ready to be promulgated for trusty and should not be listed?

see:
https://api.jujucharms.com/charmstore/v4/search?text=docker&limit=1000

**Comment by mitechie** [comment]
Just to be clear, the storefront collapsing of results should take promulgation into account to verify two charms can be collapsed. This bug is there in the code. 

In this case though, it looks like the intent is to have two promulgated block-storage-broker charms, one for precise and one for trusty.

**Comment by fabricematrat** [comment]
The main issue with that one is linked to promulgated charm not having the correct url set up.
Both url ( https://jujucharms.com/block-storage-broker/trusty/1 and  https://jujucharms.com/u/charmers/block-storage-broker/trusty/1) should be avalaible but it seems that in charmstore only the one with the owner name exist.
We will investigate the bug on charmstore.

**Comment by paulgear** [comment]
This doesn't happen just with charms; it happens with documentation links as well.  e.g. https://jujucharms.com/docs/search/?text=backup&version=1.24 gives 3 hits, the first of which 404s: https://jujucharms.com/docs/1.24/howto-backup-restore
