### ISSUE TITLE
charm telegraf not ingesting.

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#168]
I think this is an outdated charm proof (1.2.7 in charmworld) not allowing ingestion, but not sure.

http://bazaar.launchpad.net/~chris.macnaughton/charms/trusty/telegraf/trunk/revision/3

Proof from 1.2.7 says:
E: Unknown root metadata field (tags)
W: summary sould be less than 72
W: Maintainer address should contain a real-name and email only. [Chris MacNaughton chris.macnaughton@canonical.com]
W: Metadata is missing categories.
W: No icon.svg file.
W: no copyright file
I: File config.yaml not found.

I thought that the tags weren't a problem though.

**Comment by mbruzek** [comment]
I spoke with @mitechie today about this issue.  We do not believe that a charm will not ingest because of `charm proof` problems.  According to this code, http://bazaar.launchpad.net/~juju-gui-bot/charmworld/trunk/view/head:/charmworld/jobs/ingest.py#L456  only bundles that have proof errors will stop ingestion.

**Comment by urosj** [comment]
There was an issue with the ingestion process. Your charm is published now. Sorry for the inconvenience.
