### ISSUE TITLE
docs aren't as readable as they could be

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#18]
compare https://jujucharms.com/docs/ vs https://doc.cloud.online.net/howto/ssh_keys.html

The other seems much easier to read with the higher contrast. I wonder if we could look at the background/font colors and see if we can eek out some more contrast.

**Comment by Lucapaulina** [comment]
We'll look into this.

**Comment by evilnick** [comment]
It is surprising the styles worked as well as they did on docs as they weren't part of the original site. However, there are some issues mainly because of the extent and diversity of stuff that is in the docs. I have tried to supply images to illustrate the issues better.  I realise a lot of design is subjective, but I'm pretty sure the problems here are real! 
- [ ] heading styles are too similar
  ![docs1](https://cloud.githubusercontent.com/assets/115290/6513295/df7b0732-c371-11e4-926b-be2de4528be6.png)
  these are used quite a lot in the docs, and it is often confusing if you can't easily tell the difference between a heading and subheading (did we just go up a level of information again, or down, or are we in the same place?) - these just seem too close together to me 
- [ ] admonitions are rather low -key
  ![docs02](https://cloud.githubusercontent.com/assets/115290/6513438/edad7e38-c372-11e4-93fc-87c409f43e34.png)
  the admonitions are usually important notices or warnings which should stand out, but they are set in a painfully small type and look stylistically similar to the code samples. 
- [ ] everything is grey
  ![docs03](https://cloud.githubusercontent.com/assets/115290/6513580/d6b84f18-c373-11e4-9315-7dbf0e3f4b28.png)
  I don't mind the grey background, it is useful for making colourful things pop. However, on long tracts of text, the overall feeling is of a low contrast, painful read. This is made a little worse by the font. In that weight, with antialiasing on, actually more than 50% of it renders as an intermediate shade, rather than black - here is an enlarged screenshot from firefox to illustrate:
  ![docs-grey](https://cloud.githubusercontent.com/assets/115290/6513650/4b3ce790-c374-11e4-97df-acf271d870ed.png)
  I realise we want to keep the font, but perhaps we could adjust the weights or something to make it more readable on the background. Or whatever.
- [ ] syntax highlighting
  ![docs04](https://cloud.githubusercontent.com/assets/115290/6513684/a1814164-c374-11e4-8872-4d952e7015f1.png)
  the old version of the docs used syntax highlighting on the relevant code snippets. This not only made them easier to follow, but added some extra interest to otherwise, more grey.
- [ ] spacey spacing  
  ![docs05](https://cloud.githubusercontent.com/assets/115290/6513771/59bec08a-c375-11e4-97b0-989cbc49eeac.png)
  I think the spacing is a little too generous in a lot of places, particularly the leading or padding around the boxes, and between paragraphs. When lots of elements come one after another, like here, it just looks too spacey. It doesn't help that the spacing is inconsistent between practically every pair of elements.
- [ ] code in headings
  ![doc06](https://cloud.githubusercontent.com/assets/115290/6513912/8121b44c-c376-11e4-8ddd-289ddcd3bb4d.png)
  I think we should avoid using code in headings, but if it is inescapable, it probably shouldn't render exactly the same as it does in body text. I think the code in the text in general fails to stand out enough, but that may be just because of the grey issue above.

**Comment by Lucapaulina** [comment]
Thanks for the feedback Nick. We'll pick this up and make an iteration on
it soon.

**Comment by Lucapaulina** [comment]
After a meeting with @fabricematrat @spencerbygraves and @evilnick we've decided to do the following improvements.
- [ ] Speak to Ant about syntax highlighting in the docs.
- [ ] Look at making the background lighter to aid readability.
- [ ] Make the code snippets darker so they stand out from the content.
- [ ] The navigation should be changed so we expose the navigation headings and the primary nav links to the user on default view with the user able to expand the nav to show secondary and tertiary links.
- [ ] The heading styles are too similar, maybe review the copy styles to aid readability.
- [ ] Note styling needs to be higher priority. Notes should stand out as warnings.
- [ ] Spacing between elements varies and should be consistent.
- [ ] Code should not be shown in the headings.
- [ ] Review the mobile view and make sure the nav works.

Inspiration:
https://devcenter.heroku.com/articles/getting-started-with-php#view-logs
https://www.scaleway.com/docs/

**Comment by Lucapaulina** [comment]
I'm closing this issue as this is now solved, the docs will be updated with a new design which has been handed over to the dev team.
