### ISSUE TITLE
Changelog summary out of date

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#184]
http://jujucharms.com/jenkins

Note the "10 revisions", and then click "View code" and see the changelog in Launchpad itself. The jujucharms page is behind. Not sure if it's just this page or a systemic issue.

**Comment by adam-stokes** [comment]
Happening for me now too:

https://jujucharms.com/u/adam-stokes/ghost/trusty/8

**Comment by urosj** [comment]
It's an issue due to the sync between old charmworld and new charm store. Once ingestion is out of the picture (and with it the old charmworld), things should get in order again. It's a known bug and I know it's an annoying one, but we focused on new publishing instead as ingestion will get deprecated soon.

**Comment by adam-stokes** [comment]
Cool thanks for the update
