### ISSUE TITLE
Artifact when browsing jujucharms.com

### ISSUE THREAD

**Issue by lazypower** [canonical/jujucharms.com#198]
![nedge_exist___juju](https://cloud.githubusercontent.com/assets/246944/12278502/791e7a30-b94f-11e5-8ade-0d6feb474698.png)

Upon further inspection, its a flash plugin gone stray. Disabling it disabled the clipboard copy feature but removed the display artifact

**Comment by hatched** [comment]
I'm not able to reproduce this in the latest Chrome or Firefox on Ubuntu 14.04. Can you reply with your  operating system, browser, browser version.

I'm assuming this was the url you were visiting? https://jujucharms.com/u/anton-skriptsov/nedge-exist/bundle/3

**Comment by lazypower** [comment]
Sure thing hatch: OSX ElCapitan

<img width="360" alt="about" src="https://cloud.githubusercontent.com/assets/246944/12282582/1dbc1878-b96d-11e5-9ad8-2e7e8bb1d3af.png">

**Comment by anthonydillon** [comment]
Tested in Browser stack with Chrome 47 on ElCapitan and it seemed fine.

![elcapitan-google-charm-details-page](https://cloud.githubusercontent.com/assets/1413534/12294910/a42f1df0-b9f5-11e5-91e5-ad51cc8a3fe8.png)

**Comment by kadams54** [comment]
I'm pretty sure what Charles is seeing is the result of either Chrome's built-in "click to run" protection against flash objects, or maybe a third party plugin. The "click to copy" icon that the grey square appears over top of is a flash widget. In my experience Chrome's built-in stuff respects the width/height constraints set in the HTML, so that makes me lean towards third party. Regardless, we've implemented a JS-only solution in the GUI, so maybe we could bring the same to the storefront at some point.

**Comment by lazypower** [comment]
+1 to native HTML5/Javascript solutions
