### ISSUE TITLE
Videos page shows incorrect content.

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#202]
The videos page https://jujucharms.com/community/videos 

is pointing to the wrong videos, it should be grabbing everything from:

https://www.youtube.com/c/jujucharms

**Comment by castrojo** [comment]
Can we get this reprioritized? We need a working video page to publish our videos from the charm summit.

**Comment by bac** [comment]
@castrojo We are currently pulling the videos from https://insights.ubuntu.com/category/videos/feed/?tag=juju

Our web app grabs and parses that feed and constructs the page we present.  Due to production egress firewall rules we're not allowed to grab a feed from youtube.

Can you work with the web team to get the set of videos you want mirrored via that internal feed?

**Comment by castrojo** [comment]
It looks like I'll just have to post each time we upload to youtube, thanks!
