### ISSUE TITLE
"View code" link broken

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#241]
https://jujucharms.com/u/jorge/wiki-dense

Click on "Browse code", sends you to a 404 instead of where the code actually lives. Since the homepage key now handles this we should probably remove it from the site entirely.

**Comment by jrwren** [comment]
This is "fixed" but the fix is difficult to use.

Under the Actions section there is text which looks like _Home Submit a bug_  :

![screen shot 2016-06-07 at 10 34 24 am](https://cloud.githubusercontent.com/assets/106443/15861786/72721204-2c9b-11e6-95af-92d9e9b71e27.png)

Something should indicate in the UI that these are two different links and not one single link.

**Comment by anthonydillon** [comment]
This issue has intact been resolved. We removed the bug link as we don't
have extra info anymore. The home link is now on it's own and renamed to
Project.

**Comment by urosj** [comment]
@anthonydillon Where on the page provided by Jorge do we have "Project"?

**Comment by anthonydillon** [comment]
The View code has been removed with the introduction of charm push. We cannot reliably direct users to a hosted repo. The touching links have also been fixed in a follow a branch.
