### ISSUE TITLE
charmload nagios checks intermittently failing

### ISSUE THREAD

**Issue by paulgear** [canonical/jujucharms.com#247]
https://git.launchpad.net/~yellow/canonical-theblues-charms/+git/charmstore/tree/scripts/check_charmload is taking up to 35 seconds to run in some cases.  It needs to be changed to run from cron and record status in a file, then the Nagios check can just check the file.

**Comment by paulgear** [comment]
As an aside, it would be really nice if there were a pointer to this repo at https://launchpad.net/canonical-theblues-charms/

**Comment by bac** [comment]
Hi @paulgear, we recently deployed a change to the charmload process that dramatically reduces the time and load to do ingestion via the */15 cronjob.  It is routinely taking <4m rather than the 45m we'd seen earlier this week.

As a result, the load on the jc-charmstore instance is greatly reduced and the response to the query used by the nagios check is taking 2-4s, even during the window when the cronjob is known to be running.

I'd like to defer complicating the nagios check for now as I don't think it'll still be an issue.  If you agree, please close this issue.
