### ISSUE TITLE
Charm not publishing top level charm name

### ISSUE THREAD

**Issue by buggtb** [canonical/jujucharms.com#282]
Not sure if this is a bug or not. Rick H says it was, we didn't delve very deep.

charm build --series trusty
charm push ~/Projects/charms/trusty/drillbit drillbit
charm publish cs:~spicule/drillbit-<rev> -c development
charm grant cs:~spicule/drillbit-<rev> -c development  --acl read everyone

works fine, and https://jujucharms.com/u/spicule/drillbit/11 for example, resolves fine, but 
https://jujucharms.com/u/spicule/drillbit does not.

**Comment by mitechie** [comment]
Thanks for the details @buggtb. This explains things. Since the charm does not have a published stable revision, when I removed the revision number the storefront went 404 on it. I talked with the team and I think we can return a 404, but provide a better hint, especially since this is visible to everyone. Something more along the lines of "Could not find a published stable revision of the charm" or the like. 

As you noted in your deployment, to use development revisions of the charm you can deploy with --charnnel=development

With that, you should be able to upgrade charm to future development revisions easily enough. Let me know if you hit any issues with that.

**Comment by frankban** [comment]
Ok so this would be a charm store enhancement: see https://github.com/juju/charmstore/issues/637
