### ISSUE TITLE
Install section on https://jujucharms.com/get-started needs to actually install juju

### ISSUE THREAD

**Issue by timcera** [canonical/jujucharms.com#284]
I had to

```
sudo apt-get install juju
```

which isn't in the install instructions on https://jujucharms.com/get-started

**Comment by bac** [comment]
Thanks for the report @timcera.  I'm going to move this issue to the documentation project.  You can subscribe to that issue using the link below.

**Comment by evilnick** [comment]
Hi,
The instructions on the page in question seem to be valid.  The line:

`sudo apt-get install juju-quickstart juju-core`

installs Juju (`juju-core` is another name for the package, that is used to disambiguate from the old python version of Juju)

I'm mentioning this here because this isn't actually a page the docs team can directly change, so this is a more appropriate place for the bug.

**Comment by timcera** [comment]
Looks like I might have a different problem then.

This is what is happening to me.  After 

```
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:juju/stable
sudo apt-get update
sudo apt-get install juju-quickstart juju-core
```

I then enter 

```
juju quickstart mediawiki-single
```

and get the following error:

```
The program 'juju' can be found in the following packages:
 * juju-2.0
 * juju-1-default
Try: sudo apt install <selected package>
```

I am using Ubuntu 16.04

**Comment by evilnick** [comment]
Ah, yes. This is a problem with the new package names under 16.04. 
To follow the install of juju 1.25 (the stable version, which these instructions were written for):

```
  sudo apt install juju-1.25
```

For the new (still in beta, but very usable) Juju 2.0, it's best to follow the instructions here:

https://jujucharms.com/docs/devel/

**Comment by frankban** [comment]
It seems that this will be solved with the release of Juju 2.
