### ISSUE TITLE
My charm's page is missing, I get a 404 error

### ISSUE THREAD

**Issue by jhobbs** [canonical/jujucharms.com#299]
I have a tempest charm that I've uploaded to the store. It used to be visible here:
https://jujucharms.com/u/jason-hobbs/tempest/trusty

Now that gives a 404 error.

The link to it is still here:
https://jujucharms.com/u/jason-hobbs/

I haven't changed anything with it, it used to work and it just stopped working.

**Comment by anthonydillon** [comment]
This is due to removing the revisions from the search URL on the website. This had that same effect on account pages as they use the same template partial. Therefore a working link to your charm should be https://jujucharms.com/u/jason-hobbs/tempest/trusty/0. 

I am working on reverting this change when the charm is in development.
