### ISSUE TITLE
By line doesn't use the maintainer's field 

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#31]
https://jujucharms.com/cinder/trusty/

Is listed as  "By openstack-charmers", which is the owner of the charm. The maintainer field lists someone else though. 

We should probably list the maintainers in this field, not the owners.

**Comment by marcoceppi** [comment]
I can understand the want of having the "by" be the branch owner and not the maintainer in the case of when a charm is forked and the maintainer isn't updated. I feel this was a move to counter that but it appears to be an issue when charms are promulgated. Could we maybe have it so By will show maintainers on promulgated and the branch owner on unpromulgated charms?

**Comment by mitechie** [comment]
This has been a primary concern of ours for a bit. We really have been fighting using the maintainer's field because it's just not true as soon as a charm is forked and there are a lot of forks out there. We've tried to use the bzr info to tell who actually maintains the charm. 

As part of scheduled work this cycle we'll be working on making this clear and require no user involvement to keep straight.

**Comment by frankban** [comment]
This seems to be fixed.
