### ISSUE TITLE
Find new home for charmers info

### ISSUE THREAD

**Issue by huwshimi** [canonical/jujucharms.com#35]
As we migrate the docs to jujucharms.com we need a new home for the charmers info: https://juju.ubuntu.com/community/charmers/.

The page is currently referenced from here: https://jujucharms.com/docs/charm-review-process#not-part-of-the-~charmers-group?

@Lucapaulina and @marcoceppi do either of you have any thoughts?

**Comment by anthonydillon** [comment]
I believe the plan for this page is to redirect to jujucharms.com/community.

**Comment by Lucapaulina** [comment]
The plan was to redirect it to jujucharms.com/community for the time being but that is only because the page hasn't yet been migrated over. I opened an issue for it which is now closed but I can't tell if it's been completed or not, see https://github.com/CanonicalLtd/blues_browser/issues/93

@nottrobin can you give us more information on https://github.com/CanonicalLtd/blues_browser/issues/93

**Comment by Lucapaulina** [comment]
@fabricematrat pointed out that the charmers page does exist under: https://jujucharms.com/community/partners

The design needs some love and the URL is wrong.

**Comment by marcoceppi** [comment]
We can instead put this page in the docs itself

**Comment by huwshimi** [comment]
This page has now been migrated over and the url redirected, further details are being tracked in #84.
