### ISSUE TITLE
Issue with the search in the charm store with the 'Series All'

### ISSUE THREAD

**Issue by idobos71** [canonical/jujucharms.com#386]
When searching for a charm the 'Series: All' will not find/show all the charms available. 
As an example: I had an impression that the MongoDB charm does not exist for Xenial unless I chosen 'Series: Xenial 16.04' explicitly.
This issue could discourage potential Juju users from using Juju :-(

**Comment by urosj** [comment]
Hi, 
In the store, we have charms that are in global namespace (juju deploy mongodb). If such charms exist, we only guide users to them because they are guaranteed to be of good quality. User namespaced charms (the one you found under Xenial) were not subjected to testing or don't hold any guarantees, but you can by all means use them.

We're constantly looking at providing best user experience and quality and we have updates to the search experience in the pipeline.

**Comment by frankban** [comment]
We improved search to always include the ability to show community results.
Therefore I am closing this issue.
