### ISSUE TITLE
Source code to a charm hard to find from it's page

### ISSUE THREAD

**Issue by castrojo** [canonical/jujucharms.com#389]
https://jujucharms.com/u/containers/kubernetes-master/

Is there a way we can make an obvious link from the file tree to the actual source code?

**Comment by jrwren** [comment]
Right now, the homepage is set to http://kubernetes.io/, but the intent of the homepage is also to link to the homepage for the charm, which will typically link to homepage of the underlying software projects.

e.g.

charm set kubernetes-master homepage=https://github.com/kapilt/charm-kubernetes-master

**Comment by castrojo** [comment]
I know what the homepage is, I'm not looking for the homepage, I'm looking for the source code files that we list on the right sidebar.

**Comment by lazypower** [comment]
So as the author who set that URL to what we are calling the "incorrect url" - the notion of "homepage" does not tell me "github source code location" or any other VCS. It tells me that I should set the homepage of the software I'm installing so I can get more information about it. 

I think this begs the notion that we have mislabeled that data key, and it should instead be `charm-homepage` or `layer project` or any other incantation that isn't just `homepage`. That is misleading in my humble opinion.

To kind of sandbag @castrojo's comment:

If it linked to the DVCS its no longer decoupled from DVCS and has a direct dependency on that again. I don't think that is at all what was intended by severing that link. I do agree that we should add another meta key to charms to link to their respective layer properties, instead of just relying on the blobs in the API store. There's no way for a community member to contribute to that blob store, and we would instead prefer them to actively participate in the layer repositories, wherever they may be.

**Comment by jrwren** [comment]
I agree. I could quibble that "project homepage" means the homepage for the charm project, but as the charm author, I feel you should have the right to make that decision.

I would suggest that we update the storefront to include a `VCS-URL` that can be set much like the homepage, `charm set kubernetes-master vcs-url=...`. IIRC we considered this and instead we said YAGNI, these links can be added to the README.

I suggest a link in the README, preferably near the top, in bold text, or near the bottom in a section called charm development.

For comparison, the openstack charms use the `Project homepage` link to link to the github repositories for the charms, not to the upstream projects. See https://jujucharms.com/nova-compute/ and https://jujucharms.com/ceph/ for example.

**Comment by jrwren** [comment]
Update and some history:

I was browsing the charmstore today and noticed in the "Contribute" box an older charm had  "View repository" link. This sounds like what @castrojo wants. This field died with automatic ingestion from Launchpad.

The old ingestion process populated an extra-info field called bzr-url. You can populate this yourself using the charm set command. The field name is bzr-url, but it can be any URL.

e.g.
```
charm set ~evarlast/parse-server bzr-url=https://github.com/jrwren/parse-server-example
```

Now my parser-server charm has a View repository link to my github repo: https://jujucharms.com/u/evarlast/parse-server/

IIRC automatic setting of a vcs-url was not done on charm push intentionally, although I do not recall why.
