### ISSUE TITLE
We should have a process and guidelines to delete charms or revisions

### ISSUE THREAD

**Issue by mbruzek** [canonical/jujucharms.com#397]
One of our partners checked in charms with several revisions that contained usernames and passwords. 

They have fixed the problem and checked in new revisions without the username and passwords. They want the older revisions removed from the charm store.

I explained to the partner that we generally do not delete charms or revisions. This seems to be a special case where we want to honor their request.

We should develop an official policy or process for deleting or hiding the charms and or revisions.  

The UI team has been great to work with and gave me a utility to use (Thanks! I have not used it at this time). But I wanted to write down something for the next time this happens, because you know it will.

**Comment by frankban** [comment]
We are implementing the ability to remove charms from the charm store, so that we can support exceptional cases in which providers might want to delete their own charms. We'll make an announcement when this feature is ready. Closing this now, but feel free to file another issue (against juju/charmstore), if you wnat to siggest further discussion around deletion policies and practices. Thanks!
