### ISSUE TITLE
Unable to lauch bundle to demo.jujucharms.com from solution pages

### ISSUE THREAD

**Issue by arosales** [canonical/jujucharms.com#41]
For example, when I view:
https://jujucharms.com/u/bigdata-charmers/hdp-core-batch-processing/

and click on "Add to Demo" the link doesn't work and the on-hover message says, "unable to find bundle in the demo." Also should the button be grey'ed out here? Perhaps that is the signal that this shouldn't work yet?

If I try the link directly:
https://demo.jujucharms.com/?deploy-target=bundle:~bigdata-charmers/hdp-core-batch-processing-7

I also don't get the bundle to deploy.

**Comment by mitechie** [comment]
Let's talk about this one this week. This is due to the way the branch and
such are named and the changes to the bundle format/apis between charmworld
and the charmstore that runs jujucharms.com. We grey the button because we
can't figure out what the right old format bundle is.

If the naming is tweaked and fits a guessable format that matches the
bundles name in the yaml file then the button works out. That's why it's
greyed out for some bundles and not others.

Rick

**Comment by mitechie** [comment]
Marking as bug and working to get into next release. We've got work in progress on the GUI and the storefront to make sure all bundles will work properly with the 'add to demo' button using the new API. 

We expect to have this ready for a release at the start of next week.
