### ISSUE TITLE
typo in quote from EPAM  systems?

### ISSUE THREAD

**Issue by mikemccracken** [canonical/jujucharms.com#435]
At the very bottom of https://jujucharms.com just now - The section "What people are saying about Juju" has a quote from Konstantin Boudnik at EPAM that begins like this:

"Juju acts as a thing layer on top of your infrastructure that allows all your operational code to talk to each other. …"

Did he actually say "thin" layer?

**Comment by spencerbygraves** [comment]
Yes, thanks @mikemccracken

It should read “Juju acts as a thin layer on top of your infrastructure that allows all your operational code to talk to each other. And because of this communication layer, a lot of the problems that conventional configuration management systems have just don’t exist anymore.”

I'll assign @Lukewh to update it.
