### ISSUE TITLE
JS didn't pick up cleaning search url and resulting url failed to search 

### ISSUE THREAD

**Issue by mitechie** [canonical/jujucharms.com#50]
https://jujucharms.com/q/?text=apache2-subordinate

the above url should still perform the same search as

https://jujucharms.com/q/apache2-subordinate

**Comment by mitechie** [comment]
User is reporting in chromium that the search url cleaning is failing and that he's getting the ?text= url

**Comment by canonical-is** [comment]
Here is what JS console in chromium show afer I make search request:

 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi)
chrome-extension://pmoflmbbcfgacopiikdcpmbiellfihdg/base-content-script.js:99 Content script: Base content script, started on url: https://jujucharms.com/q/?text=apache2-subordinate

Content script: Base content script, started on url: https://jujucharms.com/q/?text=apache2-subordinate
chrome-extension://pmoflmbbcfgacopiikdcpmbiellfihdg/base-content-script.js:56 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
