### ISSUE TITLE
Links do not show up as such in HTML lists

### ISSUE THREAD

**Issue by pmatulis** [canonical/jujucharms.com#514]
Any link that resides within an HTML list ends up getting formatted as bold text, not as a hyperlink. See this [example](https://jujucharms.com/docs/stable/developer-getting-started) (section: 'Requirements').

**Comment by anthonydillon** [comment]
@pmatulis Thanks for reporting this. As a bit of background we set the link default styling to bold and black when in lists and tables. This was because some lists and tables were full of links and it looking unsightly. We have since moved away from this pattern with the latest Vanilla. Therefore, we can pick this up and align the link styling with Vanilla.

**Comment by anthonydillon** [comment]
@barrymcgee would you mind picking this up? We just need to replace the bespoke link styling on jujucharms docs with the latest from Vanilla.
