### ISSUE TITLE
Juju command reference docs missing anchors

### ISSUE THREAD

**Issue by ghost** [canonical/jujucharms.com#516]
The juju command reference docs could really use some anchors so people can link specific commands.

I've created an issue for the docs juju/docs#2365, but was redirected here.

**Comment by anthonydillon** [comment]
Thank you @szeestraten-ntnu. This could be an issue for either project depending on the solution. I believe this issue would be resolved by design taking a look at this section of the docs. I have suggested that each command could have its own page too make it easier to search for commands: https://github.com/CanonicalLtd/jujucharms.com/issues/515.

**Comment by pmatulis** [comment]
@anthonydillon The larger issue is that heading anchor links are not readily available to users throughout the docs.

**Comment by pmatulis** [comment]
*Not sure how I could have unassigned anyone. I don't even have the permission to do so.*

**Comment by anthonydillon** [comment]
@hatched could you choose this issue please.
