### ISSUE TITLE
wrong readme being displayed

### ISSUE THREAD

**Issue by kwmonroe** [canonical/jujucharms.com#60]
Hi friends,

Many of the apache-hadoop-\* charms have two readmes [1]:  README.md for an overview and deployment instructions, and README.dev.md for extending these charms in custom solutions.  The web is showing the dev.md, for example:

https://demo.jujucharms.com/~bigdata-dev/trusty/apache-hadoop-client-42/?text=apache-hadoop-client#readme

How is the webui choosing the readme, and more importantly, can we force it to show README.md instead?

[1] [launchpad source for sample charm with 2 readmes](http://bazaar.launchpad.net/~bigdata-dev/charms/trusty/apache-hadoop-client/trunk/files)

**Comment by mitechie** [comment]
While the charmers have suggestions for the readme file there's no forced conventions. There are readme's that are lower case, with extension, without extensions, in markdown or rst formats. We find the first file that lower cased matches the format of readme.\* which is coming up with your dev files.

I'd suggest rather than using README.dev that the file is more appropriately named something like USAGE.md, CUSTOMIZING.md, or the like. Is this not an option from the charm maintainer point of view?

**Comment by kwmonroe** [comment]
Yup, renaming *dev.md is an option for us.  I just wanted to understand how the ui was finding/displaying the readme.  Thanks for the info!
