### ISSUE TITLE
Missing charm revision

### ISSUE THREAD

**Issue by sparkiegeek** [canonical/jujucharms.com#99]
Percona Cluster charm r58 has not been "ingested".

If we look at
https://api.jujucharms.com/v4/trusty/percona-cluster/meta/extra-info/bzr-revisions

it shows latest revision as r57, but http://bazaar.launchpad.net/~openstack-charmers/charms/trusty/percona-cluster/trunk/files is showing r58

**Comment by urosj** [comment]
There's a bug in ingestion. The content is the revision r58, but bzr info
in extra info did not get updated for some reason.

See
https://api.jujucharms.com/v4/trusty/percona-cluster/meta/extra-info/bzr-digest

We'll be working on resolving the bug of course.

**Comment by mitechie** [comment]
Just to confirm. I checked the result of the bzr branch and diff'd it against the charm zip in https://api.jujucharms.com/v4/trusty/percona-cluster/archive and found the revision is there. This is a metadata issue that is known. I've added this bug link to the card so that we can update it as things are updated.
